from typing import IO
from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Profile)
admin.site.register(Indexer)
admin.site.register(Sites)
admin.site.register(Bins)
admin.site.register(Monitored_Identity)
admin.site.register(CourseOfAction)
admin.site.register(Category)
admin.site.register(STIXObjectType)
admin.site.register(STIXObjectID)
admin.site.register(STIXObject)
admin.site.register(ExternalRefrence)
admin.site.register(RelationshipType)
admin.site.register(Relationship)
admin.site.register(DefinedRelationship)
admin.site.register(ReportLabel)
admin.site.register(Report)
admin.site.register(IdentityLabel)
admin.site.register(IndustrySector)
admin.site.register(Identity)
admin.site.register(AttackPattern)
admin.site.register(AttackPatternAlias)
admin.site.register(Indicator)
admin.site.register(IndicatorLabel)
admin.site.register(IndicatorPattern)
admin.site.register(IndicatorType)
admin.site.register(ImplementationLanguages)
admin.site.register(MalwareTypes)
admin.site.register(MalwareAliases)
admin.site.register(Malware)
admin.site.register(ThreatActorRoles)
admin.site.register(ThreatActorType)
admin.site.register(ThreatActorAlias)
admin.site.register(BundleObject)
admin.site.register(ThreatActor)
admin.site.register(Sighting)
admin.site.register(Tool)
admin.site.register(ToolTypes)
admin.site.register(Vulnerability)
admin.site.register(TaxiiCollection)
admin.site.register(Campaign)
admin.site.register(CampaignAlias)
admin.site.register(IntrusionSet)
admin.site.register(IntrusionSetAlias)
admin.site.register(ObservableObjectType)
admin.site.register(ObservableObject)
admin.site.register(ObservedData)
admin.site.register(IPv4AddressObject)
admin.site.register(URLObject)
admin.site.register(DomainNameObject)
admin.site.register(FileObject)
admin.site.register(KillChainPhase)
admin.site.register(FileUpload)
admin.site.register(PlanDetails)


