# Generated by Django 3.2.8 on 2022-03-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('individual', 'individual'), ('organization', 'organization'), ('group', 'group'), ('unknown', 'unknown')], max_length=250),
        ),
        migrations.AlterField(
            model_name='stixobject',
            name='external_references',
            field=models.ManyToManyField(blank=True, to='Dashboard.ExternalRefrence'),
        ),
    ]
