# Generated by Django 3.2.8 on 2022-03-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20220324_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatorpattern',
            name='observable',
        ),
        migrations.AddField(
            model_name='indicatorpattern',
            name='pattern_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('unknown', 'unknown'), ('individual', 'individual'), ('class', 'class'), ('group', 'group')], max_length=250),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_types',
            field=models.ManyToManyField(blank=True, to='Dashboard.IndicatorType'),
        ),
    ]
