# Generated by Django 3.2.8 on 2022-03-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20220324_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrusionGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='intrusionset',
            name='resource_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('individual', 'individual'), ('organization', 'organization'), ('unknown', 'unknown'), ('class', 'class'), ('group', 'group')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('tlp', 'tlp'), ('statement', 'statement')], max_length=250),
        ),
        migrations.AddField(
            model_name='intrusionset',
            name='goals',
            field=models.ManyToManyField(blank=True, to='Dashboard.IntrusionGoals'),
        ),
    ]
