# Generated by Django 3.2.8 on 2022-03-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20220324_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalwareAliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='MalwareTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MalwareLabel',
            new_name='ImplementationLanguages',
        ),
        migrations.AlterModelOptions(
            name='implementationlanguages',
            options={},
        ),
        migrations.RenameField(
            model_name='implementationlanguages',
            old_name='value',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='malware',
            name='labels',
        ),
        migrations.AddField(
            model_name='malware',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malware',
            name='implementation_languages',
            field=models.ManyToManyField(blank=True, to='Dashboard.ImplementationLanguages'),
        ),
        migrations.AddField(
            model_name='malware',
            name='is_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='malware',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malware',
            name='sample_refs',
            field=models.ManyToManyField(blank=True, to='Dashboard.STIXObjectID'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual'), ('group', 'group'), ('class', 'class'), ('unknown', 'unknown')], max_length=250),
        ),
        migrations.AddField(
            model_name='malware',
            name='aliases',
            field=models.ManyToManyField(blank=True, to='Dashboard.MalwareAliases'),
        ),
        migrations.AddField(
            model_name='malware',
            name='malware_types',
            field=models.ManyToManyField(blank=True, to='Dashboard.MalwareTypes'),
        ),
    ]
