# Generated by Django 3.2.8 on 2022-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20220324_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('organization', 'organization'), ('unknown', 'unknown'), ('group', 'group'), ('individual', 'individual')], max_length=250),
        ),
        migrations.AddField(
            model_name='report',
            name='report_types',
            field=models.ManyToManyField(blank=True, to='Dashboard.ReportTypes'),
        ),
    ]
