# Generated by Django 3.2.8 on 2022-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20220324_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatActorGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ThreatActorLabel',
            new_name='ThreatActorRoles',
        ),
        migrations.AlterModelOptions(
            name='threatactoralias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='threatactorroles',
            options={},
        ),
        migrations.RenameField(
            model_name='threatactorroles',
            old_name='value',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='threatactor',
            name='labels',
        ),
        migrations.AddField(
            model_name='threatactor',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='resource_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='roles',
            field=models.ManyToManyField(blank=True, to='Dashboard.ThreatActorRoles'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('organization', 'organization'), ('group', 'group'), ('unknown', 'unknown'), ('individual', 'individual')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('statement', 'statement'), ('tlp', 'tlp')], max_length=250),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='goals',
            field=models.ManyToManyField(blank=True, to='Dashboard.ThreatActorGoals'),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='type',
            field=models.ManyToManyField(blank=True, to='Dashboard.ThreatActorType'),
        ),
    ]
