# Generated by Django 3.2.8 on 2022-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20220324_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual'), ('group', 'group'), ('class', 'class'), ('unknown', 'unknown')], max_length=250),
        ),
    ]
