# Generated by Django 3.2.8 on 2022-03-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_identity_identity_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatactor',
            old_name='type',
            new_name='threat_actor_types',
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('class', 'class'), ('individual', 'individual'), ('unknown', 'unknown'), ('group', 'group')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('tlp', 'tlp'), ('statement', 'statement')], max_length=250),
        ),
    ]
