# Generated by Django 3.2.8 on 2022-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20220324_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sighting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('unknown', 'unknown'), ('group', 'group'), ('organization', 'organization'), ('individual', 'individual')], max_length=250),
        ),
    ]
