# Generated by Django 3.2.8 on 2022-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_auto_20220324_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('individual', 'individual'), ('class', 'class'), ('group', 'group'), ('unknown', 'unknown'), ('organization', 'organization')], max_length=250),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observed_data_refs',
            field=models.ManyToManyField(related_name='observed_data_refs', to='Dashboard.STIXObjectID'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='where_sighted_refs',
            field=models.ManyToManyField(related_name='where_sighted_ref', to='Dashboard.STIXObjectID'),
        ),
    ]
