# Generated by Django 3.2.8 on 2022-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_auto_20220324_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('unknown', 'unknown'), ('individual', 'individual'), ('group', 'group'), ('class', 'class'), ('organization', 'organization')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('tlp', 'tlp'), ('statement', 'statement')], max_length=250),
        ),
    ]
