# Generated by Django 3.2.8 on 2022-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_auto_20220324_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observeddata',
            old_name='observable_objects',
            new_name='object_refs',
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual'), ('group', 'group'), ('unknown', 'unknown'), ('class', 'class')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('statement', 'statement'), ('tlp', 'tlp')], max_length=250),
        ),
    ]
