# Generated by Django 3.2.8 on 2022-03-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_auto_20220324_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('organization', 'organization'), ('group', 'group'), ('unknown', 'unknown'), ('individual', 'individual')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('tlp', 'tlp'), ('statement', 'statement')], max_length=250),
        ),
        migrations.AlterField(
            model_name='observableobject',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.observableobjecttype'),
        ),
        migrations.AlterField(
            model_name='observeddata',
            name='object_refs',
            field=models.ManyToManyField(blank=True, to='Dashboard.ObservableObject'),
        ),
    ]
