# Generated by Django 3.2.8 on 2022-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_auto_20220324_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('individual', 'individual'), ('unknown', 'unknown'), ('organization', 'organization'), ('group', 'group'), ('class', 'class')], max_length=250),
        ),
        migrations.AlterField(
            model_name='observableobject',
            name='spec_version',
            field=models.CharField(default='2.1', max_length=5),
        ),
        migrations.AlterField(
            model_name='stixobject',
            name='spec_version',
            field=models.CharField(default='2.1', max_length=5),
        ),
    ]
