# Generated by Django 3.2.8 on 2022-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_auto_20220324_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('group', 'group'), ('individual', 'individual'), ('class', 'class'), ('unknown', 'unknown'), ('organization', 'organization')], max_length=250),
        ),
        migrations.CreateModel(
            name='BundleObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100, unique=True)),
                ('objects', models.ManyToManyField(blank=True, to='Dashboard.STIXObjectID')),
            ],
        ),
    ]
