# Generated by Django 3.2.8 on 2022-03-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_auto_20220324_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleobject',
            name='object_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='Dashboard.stixobjectid'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('group', 'group'), ('individual', 'individual'), ('class', 'class'), ('organization', 'organization'), ('unknown', 'unknown')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('tlp', 'tlp'), ('statement', 'statement')], max_length=250),
        ),
    ]
