# Generated by Django 3.2.8 on 2022-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_auto_20220405_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('individual', 'individual'), ('unknown', 'unknown'), ('group', 'group'), ('class', 'class')], max_length=250),
        ),
    ]
