# Generated by Django 3.2.8 on 2022-05-02 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0027_auto_20220413_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan_exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan_init',
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('organization', 'organization'), ('group', 'group'), ('unknown', 'unknown'), ('individual', 'individual'), ('class', 'class')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('statement', 'statement'), ('tlp', 'tlp')], max_length=250),
        ),
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Gold', 'Gold'), ('Plantinum', 'Plantinum'), ('Silver', 'Silver')], default='', max_length=20)),
                ('plan_init', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('plan_exp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
