# Generated by Django 3.2.8 on 2022-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_auto_20220606_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='date_added',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('organization', 'organization'), ('unknown', 'unknown'), ('individual', 'individual'), ('group', 'group')], max_length=250),
        ),
    ]
