# Generated by Django 3.2.8 on 2022-06-07 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0032_auto_20220607_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='identity_class',
            field=models.CharField(choices=[('class', 'class'), ('organization', 'organization'), ('individual', 'individual'), ('unknown', 'unknown'), ('group', 'group')], max_length=250),
        ),
        migrations.AlterField(
            model_name='markingdefinition',
            name='definition_type',
            field=models.CharField(choices=[('tlp', 'tlp'), ('statement', 'statement')], max_length=250),
        ),
        migrations.AlterField(
            model_name='plandetails',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
